### ISSUE TITLE
error when validating station with regions key

### ISSUE THREAD

**Issue by juliuste** [public-transport/validate-fptf#1]
Validating this station
```js
{
	type: 'station',
	id: '123456',
	name: 'Hauptbahnhof',
	location: {
		type: 'location',
		latitude: 45,
		longitude: 13
	},
	regions: ['1234']
}
```
Fails with
```sh
AssertionError [ERR_ASSERTION]: objregions[1] must be a string
    at validateReference (/node_modules/validate-fptf/lib/reference.js:9:5)
    at recurse (/node_modules/validate-fptf/index.js:45:7)
    at validateStation (/node_modules/validate-fptf/station.js:32:7)
    at recurse (/node_modules/validate-fptf/index.js:43:7)
    at validate (/node_modules/validate-fptf/index.js:53:10)
    at Object.<anonymous> (/test.js:21:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

Same thing happens for regions with `stations` key.

**Comment by derhuerst** [comment]
PR welcome.

**Comment by juliuste** [comment]
I find your code pretty hard to read/understand, so its probably easier if you fix it yourself.

**Comment by derhuerst** [comment]
I'm not if there's a way to make the code significantly simpler. Will fix this one though.

**Comment by juliuste** [comment]
Thanks!

**Comment by juliuste** [comment]
> Same thing happens for regions with stations key.

Not fixed yet, I'll PR.
